FROM mysql:8.0

COPY init/*.sql /docker-entrypoint-initdb.d/

RUN echo "[mysqld]" > /etc/mysql/conf.d/prod.cnf && \
    echo "max_connections=200" >> /etc/mysql/conf.d/prod.cnf && \
    echo "innodb_buffer_pool_size=1G" >> /etc/mysql/conf.d/prod.cnf && \
    echo "slow_query_log=1" >> /etc/mysql/conf.d/prod.cnf

EXPOSE 3306